name = "zhongcheng-law-firm"
pages_build_output_dir = "."

[[vectorize]]
binding = "VECTORIZE"
index_name = "labor-law-qwen3-index"

[[vectorize]]
binding = "INSURANCE_VECTORIZE"
index_name = "insurance-law-qwen3-index"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "zhongcheng-db"
database_id = "ed180f05-8cba-4e04-895e-4207fb178676"
